GET http://localhost:5138/api/game?pageNumber=2


### Get by Id
GET http://localhost:5138/api/game/20


### Get by Name
GET http://localhost:5138/api/game/_searchByName?name=Asphalt


### POST
POST http://localhost:5138/api/game
Content-Type: application/json
{
    "name": "",
    "genreId": 6,
    "price": 19.99,
    "releaseDate": "2027-10-15"
}

### PUT
PUT http://localhost:5138/api/game/17
Content-Type: application/json
{
    "name": "Asphalt",
    "genreId": 6,
    "price": 17.99,
    "releaseDate": "2020-10-15"
}

### Delete Games
DELETE http://localhost:5138/api/game/1