GET http://localhost:5138/api/game


### Get by Id
GET http://localhost:5138/api/game/1


### Get by Name
GET http://localhost:5138/api/game/_searchByName?name=FIFA%20201


### POST
POST http://localhost:5138/api/game
Content-Type: application/json
{
    "name": "Asphalt",
    "genreId": 6,
    "price": 19.99,
    "releaseDate": "2020-10-15"
}


### Delete Games
DELETE http://localhost:5138/api/game/1